/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../../assets/Hermetica-Room/hermetica.glb 
*/
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/src/assets/HermeticaRoom/model.glb')
  const group = useRef()

  return (

    <group {...props} ref={group} dispose={null} >
      <mesh geometry={nodes.Text.geometry} material={materials['Material.076']} position={[-0.407, 1.029, -1.425]} rotation={[Math.PI / 2, 0, 0]} scale={[0.43, 0.293, 0.293]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.074']} position={[0.263, 1.11, -1.481]} rotation={[Math.PI / 2, 0, 0]} scale={[0.825, 0.386, 0.215]} />
      <group position={[0.176, -0.198, -1.029]} scale={[0.82, 2.001, 1]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.059']} position={[0.022, -0.081, -0.005]} scale={[1.067, 0.5, 1]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.060']} position={[0.375, 0.205, -0.129]} rotation={[1.242, 0, 0]} scale={[1.22, 0.974, 0.549]} />
        <mesh geometry={nodes.Object_18002.geometry} material={materials['Material.061']} position={[-0.64, 0.172, 0.166]} rotation={[0.295, -0.017, -0.329]} scale={[0.758, 0.47, 0.907]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.062']} position={[0.744, 0.177, 0.166]} rotation={[0.173, 0.233, 0.576]} scale={[0.709, 0.604, 1.018]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.060']} position={[-0.421, 0.205, -0.134]} rotation={[1.242, 0, 0]} scale={[1.22, 0.974, 0.549]} />
      </group>
      <group position={[-1.101, -0.198, 0.575]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.82, 2.001, 0.826]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.060']} position={[-0.007, 0.199, -0.173]} rotation={[1.204, 0, 0]} scale={[1.06, 1.462, 0.585]} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.062']} position={[-0.244, 0.179, 0.143]} rotation={[0.201, -0.136, -0.867]} scale={[0.535, 0.817, 1.209]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.059']} position={[0.025, -0.068, 0.03]} rotation={[Math.PI, -1.539, Math.PI]} scale={[0.78, 0.34, 0.895]} />
      </group>
      <group position={[-1.498, 1.128, 1.041]} rotation={[0, 0, -Math.PI / 2]} scale={[1.729, 1, 1.704]}>
        <mesh geometry={nodes.Object_67.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.material_0} position={[-0.089, 0.038, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.material_0} position={[0.08, 0.038, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} position={[-0.005, 0.038, 0.09]} rotation={[1.097, 1.525, 0.45]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.material_0} position={[-0.005, 0.038, -0.091]} rotation={[1.097, 1.525, 0.45]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.material_0} position={[-0.003, 0.038, 0]} rotation={[3.118, -0.223, -1.579]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.material_0} position={[0.001, 0.038, 0]} rotation={[3.039, -1.363, -1.688]} scale={[0.009, 0.008, 0.005]} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.material_0} position={[-0.078, 0.038, 0.045]} rotation={[0.042, 0.408, 1.546]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.material_0} position={[-0.078, 0.038, -0.047]} rotation={[-0.049, -0.485, 1.537]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.material_0} position={[-0.045, 0.038, -0.077]} rotation={[-0.095, -1.118, 1.46]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.material_0} position={[-0.048, 0.038, 0.08]} rotation={[0.079, 0.851, 1.487]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.material_0} position={[0.072, 0.038, 0.047]} rotation={[-0.05, -0.494, 1.536]} scale={[0.009, 0.01, 0.003]} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.material_0} position={[0.039, 0.038, 0.077]} rotation={[-0.09, -1.034, 1.467]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.material_0} position={[0.064, 0.038, -0.048]} rotation={[0.08, 0.626, 1.457]} scale={[0.009, 0.011, 0.003]} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.material_0} position={[0.033, 0.038, -0.083]} rotation={[0.088, 0.984, 1.472]} scale={[0.009, 0.011, 0.003]} />
      </group>
      <group position={[-1.042, 0.204, -0.962]} scale={[1.553, 1.212, 1.553]}>
        <mesh geometry={nodes.Object_117.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials['Material.070']} position={[0.045, -0.1, 0.001]} scale={[0.022, 0.028, 0.022]} />
        <mesh geometry={nodes.Object_121.geometry} material={materials['Material.070']} position={[0.012, -0.067, -0.029]} rotation={[0, 1.457, 0]} scale={[0.022, 0.028, 0.022]} />
        <mesh geometry={nodes.Object_123.geometry} material={materials['Material.070']} position={[-0.018, -0.122, 0.034]} rotation={[0, -1.563, 0]} scale={[0.022, 0.028, 0.022]} />
        <mesh geometry={nodes.Object_125.geometry} material={materials['Material.070']} position={[-0.049, -0.122, 0.005]} rotation={[Math.PI, -0.122, Math.PI]} scale={[0.022, 0.028, 0.022]} />
        <mesh geometry={nodes.Object_127.geometry} material={materials['Material.071']} position={[0, -0.375, 0]} scale={[0.786, 0.326, 0.786]} />
        <mesh geometry={nodes.Object_129.geometry} material={materials['Material.070']} position={[0, -0.06, 0]} scale={0.891} />
      </group>
      <group position={[0.354, -0.46, 0.593]} scale={[1, 1, 0.788]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.Object_2_1.geometry} material={materials['Material.084']} />
      </group>
      <group position={[-1.365, 1.509, -0.844]} rotation={[Math.PI / 2, 0, 0.54]} scale={[0.667, 0.534, 0.785]}>
        <mesh geometry={nodes.Object_53.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material.063']} position={[0.174, 0.253, 0.567]} rotation={[-1.513, 0.292, 1.49]} scale={[0.692, 1.737, 0.325]} />
        <mesh geometry={nodes.Object_57001.geometry} material={materials.material_0} position={[0.074, 0.153, 0]} rotation={[0.704, 0.218, 1.752]} scale={[1.075, 0.83, 1.207]} />
        <mesh geometry={nodes.Object_59001.geometry} material={materials.material_0} position={[0.199, 0.414, 0]} rotation={[0.739, 0.199, 1.77]} scale={[1.058, 0.832, 1.224]} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.material_0} position={[0.243, 0.506, 0]} />
        <mesh geometry={nodes.Object_63001.geometry} material={materials.material_0} position={[0.126, 0.263, 0]} />
      </group>
      <group position={[-1.365, 1.509, 0.181]} rotation={[Math.PI / 2, 0, 0.54]} scale={[0.667, 0.534, 0.785]}>
        <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material.063']} position={[0.156, 0.235, 0.567]} rotation={[-1.511, 0.417, 1.484]} scale={[0.692, 1.737, 0.325]} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} position={[0.126, 0.263, 0]} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} position={[0.243, 0.506, 0]} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} position={[0.199, 0.414, 0]} rotation={[0.739, 0.199, 1.77]} scale={[1.058, 0.832, 1.224]} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.material_0} position={[0.074, 0.153, 0]} rotation={[0.704, 0.218, 1.752]} scale={[1.075, 0.83, 1.207]} />
      </group>
      <group position={[-0.159, 0.439, 0]} scale={[0.9, 1, 1]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Material.064']} />
      </group>
      <mesh geometry={nodes.Object_133.geometry} material={materials['Material.073']} position={[-0.976, 0.406, -0.979]} rotation={[0, 0, -0.363]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_135001.geometry} material={materials['Material.066']} position={[-0.976, 0.406, -1]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_137.geometry} material={materials['Material.073']} position={[-0.976, 0.406, -0.92]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_139.geometry} material={materials['Material.055']} position={[-0.997, 0.407, -1.044]} rotation={[-0.078, 0.465, 0.035]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_141.geometry} material={materials['Material.073']} position={[-1.007, 0.407, -0.945]} rotation={[0.131, -0.618, 0.116]} scale={[-0.021, -0.032, -0.04]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials['Material.073']} position={[-1.007, 0.407, -0.906]} rotation={[-0.357, -0.983, -0.429]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_145.geometry} material={materials['Material.073']} position={[-0.997, 0.407, -1.044]} rotation={[-0.078, 0.465, 0.035]} scale={[-0.021, -0.029, -0.04]} />
      <mesh geometry={nodes.Object_143.geometry} material={materials['Material.073']} position={[-0.976, 0.406, -0.946]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_157.geometry} material={materials['Material.073']} position={[-1.109, 0.407, -0.958]} rotation={[2.981, 0.84, -2.982]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_155.geometry} material={materials['Material.073']} position={[-1.109, 0.407, -1.021]} rotation={[2.981, 0.84, -2.982]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_153.geometry} material={materials['Material.073']} position={[-1.075, 0.407, -0.887]} rotation={[-2.825, -1.127, -3.076]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_151.geometry} material={materials['Material.073']} position={[-1.116, 0.406, -0.942]} rotation={[Math.PI, -0.314, Math.PI]} scale={[-0.019, -0.03, -0.037]} />
      <mesh geometry={nodes.Object_149.geometry} material={materials['Material.073']} position={[-1.116, 0.406, -0.942]} rotation={[-3.072, -0.091, 2.887]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_159.geometry} material={materials['Material.073']} position={[-1.025, 0.406, -0.92]} scale={[-0.019, -0.023, -0.036]} />
      <mesh geometry={nodes.Object_161.geometry} material={materials['Material.073']} position={[-1.09, 0.407, -0.989]} rotation={[3.032, 0.237, -3.076]} scale={[-0.021, -0.032, -0.04]} />
      <mesh geometry={nodes.Object_163.geometry} material={materials['Material.073']} position={[-1.048, 0.407, -1.044]} rotation={[-0.542, 1.245, 0.209]} scale={[-0.021, -0.025, -0.039]} />
      <mesh geometry={nodes.Object_165.geometry} material={materials['Material.073']} position={[-1.045, 0.407, -0.882]} rotation={[0.262, -1.147, 0.28]} scale={[-0.021, -0.031, -0.04]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.material_0} position={[-1.468, 1.47, -0.896]} rotation={[3.14, 0.031, -3.077]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} position={[-1.468, 1.47, 0.585]} rotation={[3.14, 0.031, -3.077]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Material.066']} position={[-1.365, 1.509, -0.169]} scale={[0.03, 0.052, 0.03]} />
      <mesh geometry={nodes.Object_131.geometry} material={materials['Material.072']} position={[-1.049, 0.344, -0.956]} scale={[-0.152, -0.098, -0.152]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.062']} position={[-1.047, 1.276, -1.515]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.056']} position={[0, 0.87, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.055']} position={[0, 0.439, 0]} />
    </group>
  )
}

useGLTF.preload('/hermetica.glb')
